'use strict';
/**
 * Lesson — the pilot-mode conversation loop.
 *
 * One learner utterance -> one model turn -> at most ONE browser action ->
 * one automatic confirm turn (speech only) with the fresh snapshot. This is
 * the narrate/highlight/yield/act/confirm loop from the pilot prompt, kept
 * honest in code: the confirm turn may highlight or look, never act, so the
 * model cannot chain state changes inside a single learner turn.
 *
 * Every session also writes a handoff artifact folder as it goes: main.tf
 * accumulates the Terraform twin of each resource-shaping step (the model's
 * "iac" field), and README.md logs every step in plain language. Written
 * incrementally, so even an abandoned session leaves a reproducible record
 * the learner can send to their developer team.
 */
const fs = require('fs');
const path = require('path');
const { buildPilotSystem } = require('../brain/pilot-prompt');

const MAX_HISTORY = 16;              // messages (8 exchanges) before trimming
const ACT_TOOLS = ['click', 'type', 'press', 'goto'];
const LOOK_TOOLS = ['highlight', 'snapshot', 'screenshot'];

class Lesson {
  constructor({ brain, pilot, transcript, speak, config, artifactsDir, log = console }) {
    this.brain = brain;
    this.pilot = pilot;
    this.transcript = transcript;
    this.speak = speak;             // (text) => void — hands speech to Anam
    this.log = log;
    this.system = buildPilotSystem(config);
    this.history = [];
    this.resources = [];            // "type: identifier" lines, teardown list
    this.busy = false;

    // Handoff artifacts: one folder per session.
    this.config = config;
    this.dir = artifactsDir || path.join(__dirname, '..', 'lesson-artifacts',
      new Date().toISOString().slice(0, 16).replace(/[:T]/g, '-'));
    this.iacBlocks = [];
    this.steps = [];
    try { fs.mkdirSync(this.dir, { recursive: true }); } catch (e) { this.log.warn?.(`[lesson] artifacts disabled: ${e.message}`); this.dir = null; }
  }

  /** Rewrite main.tf and README.md from the accumulated session state. */
  writeArtifacts() {
    if (!this.dir) return;
    try {
      if (this.iacBlocks.length) {
        const tf = [
          '# Generated by Tony during a guided AWS console lesson.',
          `# Region: ${this.config.region} · Account: ${this.config.accountAlias}`,
          '# Reproduces the resources configured in the console during this session.',
          '',
          `provider "aws" {\n  region = "${this.config.region}"\n}`,
          '',
          ...this.iacBlocks,
        ].join('\n');
        fs.writeFileSync(path.join(this.dir, 'main.tf'), `${tf}\n`);
      }
      const md = [
        `# Lesson: ${this.config.lessonGoal}`,
        '',
        `Region **${this.config.region}**, account **${this.config.accountAlias}**. Generated live by Tony; each step below happened in the AWS console.`,
        '',
        ...this.steps.map((s, i) => `${i + 1}. ${s}`),
        '',
        this.resources.length
          ? `## Resources created\n\n${this.resources.map((r) => `- ${r}`).join('\n')}\n\n\`main.tf\` in this folder reproduces them with Terraform.`
          : '_No resources were created this session._',
      ].join('\n');
      fs.writeFileSync(path.join(this.dir, 'README.md'), `${md}\n`);
    } catch (e) {
      this.log.warn?.(`[lesson] artifact write failed: ${e.message}`);
    }
  }

  record(out) {
    if (out.note) this.resources.push(out.note);
    if (out.iac && typeof out.iac === 'string') {
      this.iacBlocks.push(out.iac.trim());
      this.transcript?.log('pilot-iac', { chars: out.iac.length, blocks: this.iacBlocks.length, dir: this.dir });
    }
    if (out.say) {
      const act = out.tool ? ` _(action: ${out.tool.name}${out.tool.targetName ? ` → ${out.tool.targetName}` : ''})_` : '';
      this.steps.push(`${out.say}${act}`);
    }
    if (out.note || out.iac || out.say) this.writeArtifacts();
  }

  /** Compact per-turn user payload: learner words + fresh page state. */
  async userPayload(learnerText, event) {
    let snap;
    try {
      snap = await this.pilot.snapshot();
    } catch (e) {
      snap = { url: this.pilot.url(), title: '', tree: `(snapshot failed: ${e.message})`, truncated: false };
    }
    return JSON.stringify({
      event,
      learner: learnerText ?? null,
      resources_created: this.resources,
      page: snap,
    });
  }

  push(role, content) {
    this.history.push({ role, content });
    if (this.history.length > MAX_HISTORY) this.history.splice(0, 2);
  }

  async model({ fast = false } = {}) {
    const raw = await this.brain.pilotTurn(this.system, this.history, { fast });
    const obj = this.brain.constructor.parseJson(raw);
    if (!obj) {
      this.transcript?.log('parse-failed', { where: 'pilotTurn', raw: raw.slice(0, 400) });
      return { say: null, tool: null, note: null };
    }
    return obj;
  }

  async execute(tool) {
    const t0 = Date.now();
    try {
      switch (tool.name) {
        case 'highlight': {
          const proof = await this.pilot.highlight({ role: tool.role, name: tool.targetName, nth: tool.nth ?? 0 });
          // No rect = a pre-0.5 content script answered (its highlight dies
          // after 6s). The tab must be refreshed after an extension reload —
          // this happened silently once; never again.
          if (!proof?.rect) this.log.warn?.('[lesson] highlight returned NO PROOF — the console tab is running an old content script. Reload the extension AND refresh the tab.');
          this.transcript?.log('pilot-act', { tool: 'highlight', role: tool.role, target: tool.targetName, ok: true, rect: proof?.rect, ...(proof?.rect ? {} : { staleContentScript: true }), tookMs: Date.now() - t0 });
          return { ok: true };
        }
        case 'click':
          await this.pilot.click({ role: tool.role, name: tool.targetName, nth: tool.nth ?? 0 });
          break;
        case 'type':
          await this.pilot.type({ role: tool.role, name: tool.targetName, nth: tool.nth ?? 0 }, tool.text ?? '');
          break;
        case 'press':
          await this.pilot.press(tool.key || 'Enter');
          break;
        case 'goto': {
          const url = String(tool.url || '');
          // The physical scope wall: this browser goes to the AWS console and
          // sign-in, nowhere else — whatever the model asks.
          if (!/^https:\/\/([a-z0-9-]+\.)*(console\.aws\.amazon\.com|signin\.aws\.amazon\.com|aws\.amazon\.com)\//.test(url)) {
            throw new Error(`goto refused: ${url.slice(0, 80)} is outside the AWS console`);
          }
          await this.pilot.goto(url);
          break;
        }
        case 'snapshot':
        case 'screenshot':
          break;   // both are satisfied by the payload of the next turn
        default:
          throw new Error(`unknown tool ${tool.name}`);
      }
      this.transcript?.log('pilot-act', { tool: tool.name, role: tool.role, target: tool.targetName, ok: true, tookMs: Date.now() - t0 });
      return { ok: true };
    } catch (e) {
      this.transcript?.log('pilot-act', { tool: tool.name, role: tool.role, target: tool.targetName, ok: false, error: e.message.slice(0, 200), tookMs: Date.now() - t0 });
      return { ok: false, error: e.message.slice(0, 200) };
    }
  }

  /** One learner turn, end to end. */
  async turn(learnerText) {
    if (this.busy) { this.transcript?.log('pilot-turn', { dropped: learnerText, reason: 'busy' }); return; }
    this.busy = true;
    const t0 = Date.now();
    try {
      this.push('user', await this.userPayload(learnerText, 'learner_message'));
      const out = await this.model();
      this.push('assistant', JSON.stringify(out));

      // Highlight runs BEFORE the narration: "I've outlined it" must already
      // be true when the learner hears it (it's ~15ms through the bridge, so
      // speech isn't delayed). If it fails, the claim is never spoken — the
      // confirm turn below reports the failure and speaks the correction.
      let res = null;
      let say = out.say;
      if (out.tool?.name === 'highlight') {
        res = await this.execute(out.tool);
        if (!res.ok) say = null;
      }
      this.record({ ...out, say });
      if (say) this.speak(say);
      this.transcript?.log('pilot-turn', { learner: learnerText, say, tool: out.tool?.name ?? null, ...(say !== out.say ? { unspoken: out.say } : {}), tookMs: Date.now() - t0 });

      if (!out.tool) return;

      if (!res) res = await this.execute(out.tool);

      // The console SPA needs a beat to render after navigation — confirming
      // instantly reads the OLD page and Tony reports "nothing changed" on
      // clicks that worked (observed live twice). Let it settle first.
      if (res.ok && ['click', 'goto', 'press'].includes(out.tool.name)) {
        await new Promise((r) => setTimeout(r, 1800));
      }

      // Confirm turn: fresh snapshot, speech + look-only tools. This is where
      // "say plainly what changed; if nothing changed, say so" happens.
      // snapshot/screenshot requests get one too — "let me take a fresh look"
      // must be followed by the report, not by silence (observed live).
      // Highlight skips it: the narration already accompanied the outline.
      if (ACT_TOOLS.includes(out.tool.name) || ['snapshot', 'screenshot'].includes(out.tool.name) || !res.ok) {
        // The report loop. The first pass confirms the learner-visible action
        // on the slow brain (it may carry teaching and iac). But if a report
        // turn ITSELF asks for a fresh look ("page is still loading, let me
        // check"), loop again: settle, snapshot, and report — on the fast
        // model, because "let me take a look" followed by 17s of silence is
        // the exact thing it promised not to do (observed live). Capped so a
        // look-happy model can't spin forever.
        let event = res.ok ? `action_executed: ${out.tool.name}` : `action_failed: ${out.tool.name} — ${res.error}`;
        let fast = res.ok && ['snapshot', 'screenshot'].includes(out.tool.name);
        let hlRetried = false;
        for (let pass = 0; pass < 3; pass++) {
          this.push('user', await this.userPayload(null, event));
          const confirm = await this.model({ fast });
          this.push('assistant', JSON.stringify(confirm));
          let csay = confirm.say;
          let cres = null;
          if (confirm.tool && LOOK_TOOLS.includes(confirm.tool.name)) {
            // Same truth rule as the main turn: outline first, narrate after.
            cres = await this.execute(confirm.tool);
            if (confirm.tool.name === 'highlight' && !cres.ok) csay = null;
          } else if (confirm.tool) {
            this.transcript?.log('pilot-act', { tool: confirm.tool.name, ok: false, error: 'deferred: acting tools are not allowed on the confirm turn' });
            // Tell the model the action did NOT happen, or its narration and
            // reality diverge ("I'll navigate there now" + nothing moves —
            // observed live). Lands in context for the next learner turn.
            this.push('user', JSON.stringify({
              event: `action_deferred: your ${confirm.tool.name} was NOT executed — one action per learner turn. The page is unchanged; re-issue it on your next turn or ask the learner.`,
            }));
          }
          this.record({ ...confirm, say: csay });
          if (csay) this.speak(csay);
          this.transcript?.log('pilot-turn', { confirm: true, pass, fast, say: csay, tool: confirm.tool?.name ?? null, ...(csay !== confirm.say ? { unspoken: confirm.say } : {}), tookMs: Date.now() - t0 });
          // A confirm-turn outline that failed would have left the learner in
          // silence after their action — run ONE corrected report turn instead.
          if (confirm.tool?.name === 'highlight' && cres && !cres.ok && !hlRetried) {
            hlRetried = true;
            event = `action_failed: highlight — ${cres.error}`;
            fast = true;
            continue;
          }
          // "Let me take a fresh look" was just spoken — the look happens now
          // and the NEXT pass speaks the report. Without this, the request
          // dead-ended and Tony went silent until the learner spoke again.
          if (['snapshot', 'screenshot'].includes(confirm.tool?.name)) {
            await new Promise((r) => setTimeout(r, 1800));   // let the SPA settle
            event = `action_executed: ${confirm.tool.name} — the fresh page state is attached; report to the learner what you see now`;
            fast = true;
            continue;
          }
          break;
        }
      }
    } finally {
      this.busy = false;
    }
  }
}

module.exports = { Lesson };
